### ISSUE TITLE
Analyze meeting

### ISSUE THREAD

**Issue by jackwingsam** [bcgov/nr-fds-design#162]
**Tasks**
- [ ] Clean up transcript and add timestamps
 - remove facilitator quotes from transcript
 - remove of unnecessary filler words (um, ah, you know, like, etc)
 - use ellipses ... to condense participants' quotes
 - use square brackets [] to add context or references
 - try and keep amount of text to fit 6 lines in a standard 288px x 168px Mural rectangle stickie
 - combine quotes if 2+ participants talk about the same topic

- [ ] Transfer transcript to Mural stickies
 - transfer chat/email content to Mural board
 - Use the appropriate colour for stickies based on convention in Everything Board
 - tag stickies appropriately
 - sort stickies into topics and sub-topics

- [ ] Copy contents to Everythingboard
- [ ] Move Mural board to archive folder
- [ ] Name recording, transcript and referenced chats/emails according to convention
